### ISSUE TITLE
Criar o documento "Como se proteger de golpes ao procurar um trabalho em TI no Canada"

### ISSUE THREAD

**Issue by FelixCoutinho** [itbr-canada-community/documentos#3]
### Contexto

Criar esse documento é importante porque a busca por empregos em TI pode ser um processo bastante desafiador e competitivo, especialmente em um mercado de trabalho estrangeiro, como no Canada. É muito comum que golpistas tentem se aproveitar de pessoas que estão em busca de trabalho, oferecendo vagas falsas, pedindo dinheiro antecipado em troca de um emprego ou solicitando informações pessoais que podem comprometer a integridade do candidato. Esses tipos de fraudes podem ser muito convincentes e persuasivos, e podem facilmente enganar pessoas desavisadas ou desesperadas por um emprego. Portanto, é essencial que candidatos a empregos em TI no Canadá estejam cientes dos riscos e saibam como se proteger contra esses golpes. 

Tornar esse tipo de informação conhecida do público é um dos objetivos do ITBR Canada. 

Além disso, o documento é importante porque fornecerá aos leitores informações úteis e práticas sobre como evitar ser vítima de golpes durante a busca por empregos em TI no Canadá. O texto deve abordar tópicos como pesquisar sobre a empresa antes de se candidatar, ficar atento a ofertas de emprego suspeitas, evitar enviar informações pessoais ou dinheiro para empresas desconhecidas e verificar a autenticidade de oportunidades de trabalho oferecidas online. Ao seguir essas dicas e manter-se alerta para os riscos potenciais, os candidatos a empregos em TI no Canadá poderão reduzir significativamente suas chances de cair em golpes e aumentar suas chances de encontrar um emprego legítimo e seguro.

### Sugestões de títulos

- Não caia em armadilhas: Como se proteger de golpes durante a busca por empregos em TI no Canadá
- Fique alerta: Como se proteger de fraudes ao procurar empregos de TI no Canadá
- Procurando emprego em TI no Canadá? Saiba como se prevenir de possíveis golpes
- Proteja-se de golpes ao buscar empregos de TI no Canadá
- Dicas para evitar fraudes em empregos de TI no Canadá
- Dicas práticas para evitar golpes em empregos de TI no Canadá

### Acceptance criteria
O documento deve ser criado dentro do repositório de documentos da comunidade (https://github.com/itbr-canada-community/documentos)

**Comment by amengol** [comment]
Algumas dicas do **ChatGPT:**

Infelizmente, golpes online são uma realidade e podem afetar qualquer pessoa, incluindo novos imigrantes com high skills no Canadá. Para ajudar a evitar esses golpes, aqui estão algumas dicas de segurança que podem ser úteis:

1. Pesquise a empresa e o recrutador antes da entrevista. Verifique se a empresa e o recrutador são legítimos e se têm uma presença online estabelecida. Verifique também se a empresa está registrada junto aos órgãos regulatórios relevantes.
2. Nunca compartilhe informações pessoais, como número de Seguro Social (SIN) ou dados bancários, durante a entrevista ou com um recrutador que você não conhece bem.
3. Fique atento a ofertas de emprego que parecem boas demais para ser verdade. Golpistas muitas vezes oferecem empregos que pagam muito acima do mercado ou prometem uma posição sem requisitos de experiência ou qualificação.
4. Desconfie de ofertas de emprego que exigem que você pague alguma taxa ou envie dinheiro. Empregadores legítimos geralmente não exigem dinheiro antecipado.
5. Verifique se o endereço de e-mail do recrutador é legítimo e se o site da empresa parece profissional e atualizado. Golpistas muitas vezes usam endereços de e-mail falsos ou criam sites falsos que parecem genuínos.
6. Se você receber uma oferta de emprego, verifique se a empresa tem uma política de privacidade clara e como seus dados serão protegidos. Certifique-se de que a empresa esteja em conformidade com as leis de proteção de dados.
7. Fique atento a qualquer tipo de pressão ou urgência para fornecer informações ou tomar uma decisão imediata. Golpistas muitas vezes usam táticas de pressão para forçar a vítima a agir rapidamente.
8. Use senhas seguras e diferentes para cada conta online. Isso ajudará a proteger suas informações pessoais e evitar que os golpistas acessem suas contas.
9. Fique atento a phishing scams, como e-mails falsos que parecem ser de empresas ou organizações legítimas, mas na verdade são fraudulentos. Nunca clique em links em e-mails suspeitos e não forneça informações pessoais em sites que você não confia.
10. Se você acredita que foi vítima de um golpe, entre em contato com as autoridades competentes imediatamente, como a polícia local e o Departamento de Cidadania e Imigração do Canadá. Quanto mais cedo você denunciar o golpe, melhor será a chance de recuperar seu dinheiro e evitar que outros sejam vítimas do mesmo golpe.
